<?php
/**
 * HTTP Thermostat
 * HTTP Thermostat API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Codegen\Models;

use Illuminate\Database\Eloquent\Model;

abstract class StatusValueBase extends Model
{
    /**
     * Validate Model attributes.
     *
     * @return bool true if all validation passed.
     */
    public function valid()
    {

        return true;
    }
}
