<?php
/**
 * HTTP Thermostat
 * HTTP Thermostat API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\RESTfulAPI\Codegen;

class Routes
{
    public static function addWebRoutes()
    {
        // web routes are not supported yet.
    }

    public static function addApiRoutes()
    {
        // HTTP Thermostat (1.0.0)
        \Route::get('/api/thermostat/{name}/auto', '\App\RESTfulAPI\Controllers\HttpthermostatApi@autoWithValidate');
        \Route::get('/api/thermostat/{name}/comfort', '\App\RESTfulAPI\Controllers\HttpthermostatApi@comfortWithValidate');
        \Route::get('/api/thermostat/{name}/no-frost', '\App\RESTfulAPI\Controllers\HttpthermostatApi@noFrostWithValidate');
        \Route::get('/api/thermostat/{name}/off', '\App\RESTfulAPI\Controllers\HttpthermostatApi@offWithValidate');
        \Route::get('/api/thermostat/{name}/status', '\App\RESTfulAPI\Controllers\HttpthermostatApi@statusWithValidate');
        \Route::get('/api/thermostat/{name}/targetHeatingCoolingState/{state}', '\App\RESTfulAPI\Controllers\HttpthermostatApi@targetHeatingCoolingStateWithValidate');
        \Route::get('/api/thermostat/{name}/targetRelativeHumidity/{humidity}', '\App\RESTfulAPI\Controllers\HttpthermostatApi@targetRelativeHumidityWithValidate');
        \Route::get('/api/thermostat/{name}/targetTemperature/{temp}', '\App\RESTfulAPI\Controllers\HttpthermostatApi@targetTemperatureWithValidate');
    }
}
